services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend/lambda_app
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/lambda_app/.env
    depends_on:
      - mongo
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongo-data:
